const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const layer=fs.readFileSync(path.join(root,'static/capture_integrity_layer.js'),'utf8');
const temporal=fs.readFileSync(path.join(root,'static/temporal_evidence_layer.js'),'utf8');
const worker=fs.readFileSync(path.join(root,'static/temporal_evidence_worker.js'),'utf8');
const html=fs.readFileSync(path.join(root,'static/index.html'),'utf8');
assert(layer.includes("VERSION='BLE4.3.8.2'"));
assert(layer.includes('TemporalEvidenceLayer?.openRole'));
assert(layer.includes('TemporalEvidenceLayer?.release'));
assert(layer.includes('TemporalEvidenceLayer?.beginCycle'));
assert(layer.includes("filter(e=>e.epochMs>=c.startedAt-220"),'current cycle must reject historical timeline events');
assert(layer.includes("source='rearm-wait-neutral-edge'"),'re-arm gate must block residual post-shot Set');
assert(temporal.includes("new Worker('/static/temporal_evidence_worker.js?v=ble43890')"));
assert(worker.includes('MediaStreamTrackProcessor'));
assert(worker.includes('OffscreenCanvas'));
assert(worker.includes('processor_discarded_frames'));
assert(html.indexOf('temporal_evidence_core.js')<html.indexOf('capture_integrity_layer.js'));
assert(html.indexOf('temporal_evidence_layer.js')<html.indexOf('native_capture_layer.js'));
assert(html.indexOf('native_capture_layer.js')<html.indexOf('pose.js'));
console.log('BLE4.3.8 native + browser temporal integration static QA PASS');
