const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const cap=fs.readFileSync(path.join(root,'static','capture_integrity_layer.js'),'utf8');
const nat=fs.readFileSync(path.join(root,'static','native_capture_layer.js'),'utf8');
const polish=fs.readFileSync(path.join(root,'static','field_polish_layer.js'),'utf8');
const html=fs.readFileSync(path.join(root,'static','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'static','style.css'),'utf8');
const launcher=fs.readFileSync(path.join(root,'../internal/start_analyzer.sh'),'utf8');
const wrapper=fs.readFileSync(path.join(root,'../internal/start_services.sh'),'utf8');
const swift=fs.readFileSync(path.join(root,'native_capture_bridge','3PMNativeCaptureBridge.swift'),'utf8');
assert(cap.includes("VERSION='BLE4.3.8.2'"));
assert(cap.includes("cycle_rearm:'provisional motion stays Set; verified Setup may abort to Set; verified Draw+ is monotonic; terminal lock + neutral-confirmed let-down -> Set/Ready'"));
assert(cap.includes('rearmNeutralSamples>=3'));
assert(cap.includes('t-rearmNeutralSince>=100'));
assert(cap.includes('pinned_diagnostics:run.diagnosticClips'));
assert(cap.includes('releaseCandidateGrowth'));
assert(cap.includes('pinCycleDiagnostics'));
assert(nat.includes("targetAddressSpace:'loopback'"));
assert(nat.includes('3pm_native_capture_state.json'));
assert(swift.includes('Access-Control-Allow-Private-Network: true'));
assert(wrapper.includes('-sectcreate -Xlinker __TEXT -Xlinker __info_plist'));
assert(wrapper.includes('write_capture_state "ready"'));
assert(launcher.includes('THREEPM_FORM_NO_BROWSER=1'));
assert(!launcher.includes('for _ in 1 2 3 4; do'));
assert(polish.includes("FRAMING READY"));
assert(css.includes('.framing-guide.framing-ready span'));
assert(html.includes('/static/field_polish_layer.js?v=ble4382'));
console.log('BLE4.3.8.2 field polish static contract: PASS');
