'use strict';
const fs=require('fs'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'static/index.html'),'utf8');
const layer=fs.readFileSync(path.join(root,'static/foundation_guard_layer.js'),'utf8');
const start=fs.readFileSync(path.join(root,'../internal/start_analyzer.sh'),'utf8');
const ci=fs.readFileSync(path.join(root,'static/capture_integrity_layer.js'),'utf8');
assert(start.includes('BUILD_TAG="mac-20261001-r8-merge-candidate-dev"'),'launcher build tag is stale');
assert(start.includes('&launch=$(date +%s)'),'per-launch root cache buster missing');
assert(start.includes("EXPECTED_CAPTURE_BUILD=\"const BUILD_VERSION='BLE4.3.8.9.5.4';\""),'runtime version preflight missing');
assert(ci.includes("const BUILD_VERSION='BLE4.3.8.9.5.4';"),'trace integration version missing');
assert(html.includes('data-phase="Setup">Set</div>'),'internal Setup must display as Set');
assert(html.includes('data-phase="Set">Setup</div>'),'internal Set must display as Setup');
assert(!html.includes('phase-live-current" data-phase="Setup"'),'first phase must not be green before runtime confirmation');
assert(layer.includes("const DISPLAY_PHASE={Setup:'Set',Set:'Setup'"),'display phase mapping missing');
assert(layer.includes('const firstPhaseConfirmed=!!snap.confirmed.Setup'),'neutral phase guard missing');
for(const m of ['side_lifecycle_core.js?v=ble438954','adaptive_release_core.js?v=mac20260930r7','foundation_guard_core.js?v=ble43888','capture_integrity_layer.js?v=mac20260930r7','evidence_timeline_baseline_layer.js?v=mac20260930r7','foundation_guard_layer.js?v=mac20260930r7','app.js?v=ble43888'])assert(html.includes(m),`runtime cache key missing ${m}`);
for(const m of ['native_vision_shadow_core.js?v=hv1','camera_timeline_core.js?v=hv3','evidence_integrity_repair_layer.js?v=hv2','native_capture_layer.js?v=hv3','multicamera_timeline_layer.js?v=hv3','native_vision_shadow_layer.js?v=hv1'])assert(html.includes(m),`HV3 runtime module missing ${m}`);
console.log('R8 merge runtime truth QA PASS');
