'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'static/index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'static/app.js'),'utf8');
const ci=fs.readFileSync(path.join(root,'static/capture_integrity_layer.js'),'utf8');
const css=fs.readFileSync(path.join(root,'static/style.css'),'utf8');
const launcher=fs.readFileSync(path.join(root,'../internal/start_services.sh'),'utf8');
for(const m of ['review_precision_layer.js?v=ble43888','evidence_timeline_baseline_layer.js?v=mac20260930r7','side_lifecycle_core.js?v=ble438954','adaptive_release_core.js?v=mac20260930r7','foundation_guard_core.js?v=ble43888','capture_integrity_layer.js?v=mac20260930r7','app.js?v=ble43888','style.css?v=ble438941'])assert(html.includes(m),`cache/wiring missing ${m}`);
assert(html.indexOf('adaptive_release_core.js?v=mac20260930r7')<html.indexOf('capture_integrity_layer.js?v=mac20260930r7'),'adaptive sentinel must load before capture integration');
for(const m of ['Building Baseline · ${n}/3','Baseline Ready ✓ · 3/6','Baseline refining · ${n}/6','Baseline Refined ✓ · 6 verified shots','Session Calibration Complete'])assert(app.includes(m),`calibration state missing ${m}`);
assert(app.includes('Math.abs(t-Number(prev.epochMs))<=25'),'persisted evidence near-duplicate filter missing');
assert(app.includes('Math.abs(mt-st.lastMediaTime)<0.0008'),'decoded mediaTime duplicate filter missing');
assert(app.includes('targetCount=15'),'15-keyframe summary contract missing');
assert(ci.includes('AdaptiveReleaseCore'),'adaptive release integration missing');
for(const m of ['coach_keyframe25_backfill_core.js?v=ble438941','coach_keyframe25_backfill_layer.js?v=mac20260930r7','camera_fps_guard_core.js?v=ble438941','camera_fps_guard_layer.js?v=ble438941'])assert(html.includes(m),`BLE438941 adaptive/backfill wiring missing ${m}`);
assert(ci.includes("activity_detection:'diagnostic-only-hidden-never-gates-capture'"),'activity classifier must remain diagnostic-only');
assert(css.includes('.phase-pill.phase-live-current')&&css.includes('.phase-pill.phase-complete')&&css.includes('.phase-pill.phase-upcoming'),'monotonic phase colors missing');
assert(launcher.includes('SWIFTC_FOUND')&&launcher.includes('MACOSX_DEPLOYMENT_TARGET=13.0')&&launcher.includes('-module-cache-path "$RUNTIME_DIR/swift-module-cache-capture"'),'native helper SDK/toolchain retry missing');
assert(ci.includes("const BUILD_VERSION='BLE4.3.8.9.5.4';"),'exported trace version truth missing');
console.log('BLE4.3.8.9.4.1 integration/static contract QA PASS');
