'use strict';
const {frameUID}=require('../../shadow/contracts/identity');
const H='a'.repeat(64);
function arrival(n=0){return {clockId:'arrival-clock',ticks:String(n),timebase:{numerator:'1',denominator:'1000000'},masterTime:n,mappingId:null};}
function frame(seq=1,{runId='r',masterClockId='m',role='side',sourceId='cam',streamGeneration='g',sourcePTS=undefined,mappedMasterTime=null,contentDigest=null,payloadRef=null,decodeValid=false,measuredFPS=30}={}){
 if(sourcePTS===undefined)sourcePTS=mappedMasterTime===null?null:String(mappedMasterTime);
 const f={schemaVersion:'3pm.analyzer.shadow.v1',recordKind:'frame',runId,createdByVersion:'test-v1',role,sourceId,streamGeneration,frameSeq:String(seq),frameUID:'',identityKind:'source-sample',sourcePTS,sourceTimebase:sourcePTS===null?null:{numerator:'1',denominator:'1000000'},clockId:'clk',timestampKind:sourcePTS===null?'unknown':'presentation',sourceTimeMissingReason:sourcePTS===null?'fixture_missing':null,masterClockId,mappedMasterTime,mappingUncertainty:mappedMasterTime===null?null:0,mappingId:mappedMasterTime===null?null:'map',mappingVersion:mappedMasterTime===null?null:1,mappingStatus:mappedMasterTime===null?'unmapped':'validated',arrivalTime:arrival(mappedMasterTime??Number(seq)),width:640,height:480,rotation:0,mirror:null,pixelFormat:'rgba',nominalFPS:measuredFPS,measuredFPS,quality:{decodeValid,trackingConfidence:null,blurScore:null,exposureClipped:null,qualitySchema:'q',flags:[]},dropCounters:{source:null,transport:null,encoder:null,counterScope:streamGeneration},backend:{id:'replay',version:'1',platform:'offline',adapterInstanceId:`a:${sourceId}:${streamGeneration}`},payloadRef,payloadState:payloadRef?'available':'unavailable',transformId:'identity',contentDigest};
 f.frameUID=frameUID(f);return f;
}
function candidate(seq=1,t=0,extra={}){const runId=extra.runId||'r',sourceId=extra.sourceId||'cam',streamGeneration=extra.streamGeneration||'g';const uid=frameUID({runId,sourceId,streamGeneration,frameSeq:String(seq)});return {candidateId:`c${seq}-${extra.derivationId||'d'}`,frameUID:uid,frameEnvelopeRef:`frame/${uid}`,frameSeq:String(seq),sourcePTS:extra.sourcePTS??String(t),derivationId:extra.derivationId||'d',runId,cycleId:extra.cycleId||'c',role:extra.role||'side',masterClockId:extra.masterClockId||'m',sourceId,streamGeneration,payloadRef:extra.payloadRef||`blob/${seq}`,payloadState:'available',contentDigest:extra.contentDigest||H,actualMasterTime:t,mappingStatus:'validated',mappingUncertainty:extra.mappingUncertainty??0,decodeValid:true,width:extra.width||10,height:extra.height||10,measuredFPS:extra.measuredFPS??30,phaseEvidenceRefs:extra.phaseEvidenceRefs||[],...extra,frameUID:uid,frameSeq:String(seq),runId,sourceId,streamGeneration};}
function binding({sourceId='cam',streamGeneration='g',startMasterTime=-1000000,endMasterTime=10000000,capturePeriodUs=33333,jitterUs=0}={}){return {sourceId,streamGeneration,startMasterTime,endMasterTime,capturePeriodUs,jitterUs};}
function mapping(extra={}){return {mappingId:'map',version:1,runId:'r',masterClockId:'m',clockId:'clk',streamGeneration:'g',sourceTimebase:{numerator:'1',denominator:'1000000'},scale:{numerator:'1',denominator:'1'},driftBoundPpm:0,offsetUs:0,validStartTick:'0',validEndTick:'10000000',calibrationMethod:'fixture',calibrationSampleIds:['s1'],residualBoundUs:0,transportBoundUs:0,uncertaintyBoundUs:0,timestampKind:'presentation',status:'validated',createdByVersion:'test-v1',mappingNamespace:'shadow/replay/test',trustedApiId:null,supersedes:null,...extra};}
module.exports={H,arrival,frame,candidate,binding,mapping};
