'use strict';
const assert=require('assert'),crypto=require('crypto');
const {buildReviewView,anchorTarget,playbackOrder}=require('../../shadow/review/view_model');
const {project25}=require('../../shadow/projector/logical25');
const {buildArchive,validateArchive,roundTrip,InMemoryArchiveImporter}=require('../../shadow/archive/shadow_archive');
const F=require('./_shadow_fixture');
const baseline=crypto.createHash('sha256').update('baseline').digest('hex'),bytes=Buffer.from([1,2,3]),digest=crypto.createHash('sha256').update(bytes).digest('hex');
const c=F.candidate(1,75000,{payloadRef:'frames/1.bin',contentDigest:digest,phaseEvidenceRefs:['fake-claim']});const f=F.frame(1,{mappedMasterTime:75000,payloadRef:'frames/1.bin',contentDigest:digest,decodeValid:true});
const timeline={masterClockId:'m',anchor:{status:'verified',start:0,end:300000,refs:['timeline-anchor']}};const p=project25({runId:'r',cycleId:'c',masterClockId:'m',role:'side',timeline,candidates:[c],roleBindings:[F.binding({startMasterTime:0,endMasterTime:300000,capturePeriodUs:100000,jitterUs:0})],projectionId:'p',configDigest:'cfg'});const view=buildReviewView(p);assert.equal(anchorTarget(view).status,'real');assert.equal(anchorTarget(view).frameUID,c.frameUID);assert.deepEqual(playbackOrder(p),[c.frameUID]);
const bad=JSON.parse(JSON.stringify(p));const real=bad.slots.find(s=>s.status==='real');if(real){const another=bad.slots.find(s=>s.status==='missing'&&Number.isSafeInteger(s.targetMasterTime));Object.assign(another,{status:'real',actualFrameUID:real.actualFrameUID,derivationId:real.derivationId,candidateId:real.candidateId,actualMasterTime:another.targetMasterTime,signedDelta:0,missingReason:null,mappingUncertaintyUs:0,toleranceUs:50000,actualPhaseEvidenceRefs:['x'],selectionReason:'fake',sourceId:real.sourceId,streamGeneration:real.streamGeneration,frameSeq:real.frameSeq,contentDigest:real.contentDigest,frameEnvelopeRef:real.frameEnvelopeRef});bad.uniqueRealCount++;bad.missingCount--;assert.throws(()=>buildReviewView(bad),/duplicate|FrameUID/);}
const records={frames:[f],candidates:[c],events:[],projections:[p],timelines:[{projectionId:'p',timeline,releaseTime:null}]};const arc=buildArchive({archiveId:'a1',baselineDigest:baseline,records,files:{'frames/1.bin':bytes}});assert(validateArchive(arc));assert(validateArchive(roundTrip(arc)));const tam=JSON.parse(JSON.stringify(arc));tam.payloads['../../evil']='AAAA';assert.throws(()=>validateArchive(tam),/UNLISTED/);assert.throws(()=>buildArchive({archiveId:'bad',baselineDigest:baseline,records:{frames:[],candidates:[],events:[],projections:[]},files:{'Frame.jpg':Buffer.from('1'),'frame.jpg':Buffer.from('2')}}),/colliding/);assert.throws(()=>buildArchive({archiveId:'bad2',baselineDigest:baseline,records:{frames:[],candidates:[],events:[],projections:[]},files:{'CON':Buffer.from('1')}}),/unsafe/);const importer=new InMemoryArchiveImporter();assert.equal(importer.stage(arc,{namespace:'shadow/import'}).status,'staged');assert.equal(importer.stage(arc,{namespace:'shadow/import'}).status,'existing');assert.throws(()=>importer.stage(arc,{namespace:'production'}),/shadow namespace/);
console.log('P1-06 review/archive hardened: PASS');
