'use strict';
const {immutablePlainCopy,isId}=require('../contracts/strict_types');
const {validateEvidenceCandidate}=require('../contracts/record_validators');
const {sha256Canonical}=require('../contracts/canonical_json');
const PLAN='logical25-v1-shadow';
const SLOT_PLAN=[...[['draw',1/3],['draw',2/3]],...[['anchor',1/4],['anchor',1/2],['anchor',3/4]],...[['hold',1/4],['hold',1/2],['hold',3/4]],...[['expansion',1/3],['expansion',2/3]],...Array.from({length:9},(_,i)=>['release_window',i-4]),...Array.from({length:5},(_,i)=>['follow_through',(i+1)/6]),['recovery',1]];
function phaseInterval(timeline,name){const p=timeline?.[name];return p&&p.status==='verified'&&Number.isSafeInteger(p.start)&&Number.isSafeInteger(p.end)&&p.end>=p.start&&Array.isArray(p.refs)&&p.refs.every(isId)?p:null;}
function slotTargets({timeline={},releaseTime=null}){return SLOT_PLAN.map(([phase,pos],i)=>{let target=null,refs=[];if(phase==='release_window'){if(Number.isSafeInteger(releaseTime))target=releaseTime+pos*33333;const p=timeline?.release_window;if(p?.status==='verified'&&Array.isArray(p.refs))refs=[...p.refs];}else{const iv=phaseInterval(timeline,phase);if(iv){target=phase==='recovery'?iv.end:Math.round(iv.start+(iv.end-iv.start)*pos);refs=[...iv.refs];}}return {slotId:`S${String(i+1).padStart(2,'0')}`,phase,targetMasterTime:target,targetPhaseEvidenceRefs:refs};});}
function bindingKey(c){return `${c.sourceId}\u0000${c.streamGeneration}`;}
function normalizeBindings(roleBindings){if(!Array.isArray(roleBindings)||roleBindings.length===0)throw new TypeError('roleBindings required');const out=new Map();for(const b of roleBindings){if(!b||!isId(b.sourceId)||!isId(b.streamGeneration)||!Number.isSafeInteger(b.startMasterTime)||!(b.endMasterTime===null||Number.isSafeInteger(b.endMasterTime))||b.endMasterTime!==null&&b.endMasterTime<b.startMasterTime||!Number.isSafeInteger(b.capturePeriodUs)||b.capturePeriodUs<=0||!Number.isSafeInteger(b.jitterUs)||b.jitterUs<0)throw new TypeError('invalid role binding');const k=`${b.sourceId}\u0000${b.streamGeneration}`;if(out.has(k))throw new TypeError('duplicate role binding');out.set(k,immutablePlainCopy(b));}return out;}
function identitySignature(c){return sha256Canonical({frameUID:c.frameUID,runId:c.runId,sourceId:c.sourceId,streamGeneration:c.streamGeneration,frameSeq:c.frameSeq,sourcePTS:c.sourcePTS,contentDigest:c.contentDigest,frameEnvelopeRef:c.frameEnvelopeRef});}
function classifyCandidate(c,ctx){
  let v;try{v=validateEvidenceCandidate(c,{runId:ctx.runId,cycleId:ctx.cycleId,role:ctx.role});}catch(e){return {ok:false,reason:/payload|decode/.test(e.message)?'payload_missing':/mapping/.test(e.message)?'clock_uncertain':'candidate_invalid'};}
  if(v.masterClockId!==ctx.masterClockId)return {ok:false,reason:'clock_mismatch'};const binding=ctx.bindings.get(bindingKey(v));if(!binding)return {ok:false,reason:'generation_mismatch'};if(v.actualMasterTime<binding.startMasterTime||binding.endMasterTime!==null&&v.actualMasterTime>binding.endMasterTime)return {ok:false,reason:'generation_mismatch'};return {ok:true,value:v,binding};
}
function preflightRawUidConflicts(candidates){const seen=new Map();for(const c of candidates){if(!c||typeof c.frameUID!=='string'||!c.frameUID)continue;const sig=sha256Canonical({runId:c.runId??null,sourceId:c.sourceId??null,streamGeneration:c.streamGeneration??null,frameSeq:c.frameSeq??null,sourcePTS:c.sourcePTS??null,contentDigest:c.contentDigest??null,frameEnvelopeRef:c.frameEnvelopeRef??null});const prior=seen.get(c.frameUID);if(prior&&prior!==sig)throw new Error('FRAME_UID_CONFLICT');if(!prior)seen.set(c.frameUID,sig);}}
function bestDerivations(validRows){const by=new Map();for(const row of validRows){const c=row.value,k=c.frameUID,prior=by.get(k),sig=identitySignature(c);if(prior&&prior.identitySignature!==sig)throw new Error('FRAME_UID_CONFLICT');if(!prior){by.set(k,{...row,identitySignature:sig});continue;}const ar=c.width*c.height,br=prior.value.width*prior.value.height;if(ar>br||(ar===br&&String(c.derivationId).localeCompare(String(prior.value.derivationId))<0))by.set(k,{...row,identitySignature:sig});}return [...by.values()].sort((a,b)=>String(a.value.frameUID).localeCompare(String(b.value.frameUID))||String(a.value.derivationId).localeCompare(String(b.value.derivationId)));}
function tolerance(row){return Math.min(50000,Math.ceil(row.binding.capturePeriodUs/2+row.binding.jitterUs+row.value.mappingUncertainty));}
function eligible(slot,row,timeline){const c=row.value,tol=tolerance(row);if(!Number.isSafeInteger(slot.targetMasterTime))return {ok:false,tolerance:tol};if(Math.abs(c.actualMasterTime-slot.targetMasterTime)>tol)return {ok:false,tolerance:tol};if(slot.phase==='release_window')return {ok:true,tolerance:tol};const iv=phaseInterval(timeline,slot.phase);return {ok:!!iv&&c.actualMasterTime-c.mappingUncertainty>=iv.start&&c.actualMasterTime+c.mappingUncertainty<=iv.end,tolerance:tol};}
function minCostLexMatch(slots,rows,timeline){
  const S=0,slot0=1,frame0=slot0+slots.length,T=frame0+rows.length,N=T+1,adj=Array.from({length:N},()=>[]);function edge(u,v,cap,cost){const a={v,cap,cost,rev:adj[v].length},b={v:u,cap:0,cost:-cost,rev:adj[u].length};adj[u].push(a);adj[v].push(b);}slots.forEach((_,i)=>edge(S,slot0+i,1,0n));rows.forEach((_,j)=>edge(frame0+j,T,1,0n));
  const B=BigInt(rows.length+2),sentinel=BigInt(rows.length+1);const powers=Array(slots.length);let p=1n;for(let i=slots.length-1;i>=0;i--){powers[i]=p;p*=B;}const maxLex=sentinel*p,PRIMARY=maxLex+1n;
  slots.forEach((s,i)=>rows.forEach((r,j)=>{const e=eligible(s,r,timeline);if(e.ok){const delta=BigInt(Math.abs(r.value.actualMasterTime-s.targetMasterTime));const digit=BigInt(j+1);const lex=(digit-sentinel)*powers[i];edge(slot0+i,frame0+j,1,delta*PRIMARY+lex);}}));
  while(true){const dist=Array(N).fill(null),pv=Array(N).fill(-1),pe=Array(N).fill(-1),inq=Array(N).fill(false),q=[S];dist[S]=0n;inq[S]=true;while(q.length){const u=q.shift();inq[u]=false;for(let ei=0;ei<adj[u].length;ei++){const e=adj[u][ei];if(e.cap<=0||dist[u]===null)continue;const nd=dist[u]+e.cost;if(dist[e.v]===null||nd<dist[e.v]){dist[e.v]=nd;pv[e.v]=u;pe[e.v]=ei;if(!inq[e.v]){q.push(e.v);inq[e.v]=true;}}}}if(dist[T]===null)break;for(let v=T;v!==S;v=pv[v]){const e=adj[pv[v]][pe[v]];e.cap--;adj[v][e.rev].cap++;}}
  const out=new Map();for(let i=0;i<slots.length;i++)for(const e of adj[slot0+i])if(e.v>=frame0&&e.v<T&&e.cap===0)out.set(i,e.v-frame0);return out;
}
function project25({runId,cycleId,masterClockId,role,active=true,timeline={},releaseTime=null,candidates=[],projectionId='projection-1',projectionVersion=1,planVersion=PLAN,roleBindings,configDigest='shadow-default'}={}){
  if(!isId(runId)||!isId(cycleId)||!isId(masterClockId)||!['side','overhead','rear'].includes(role)||!isId(projectionId)||!isId(configDigest))throw new TypeError('projection identity required');const hasVerifiedTimeline=Object.entries(timeline||{}).some(([k,v])=>k!=='masterClockId'&&v&&v.status==='verified');if(hasVerifiedTimeline&&timeline.masterClockId!==masterClockId)throw new Error('TIMELINE_CLOCK_MISMATCH');const slots=slotTargets({timeline,releaseTime});const baseSlot=s=>({...s,runId,cycleId,masterClockId,role,projectionId,projectionVersion,planVersion});
  if(!active){const rows=slots.map(s=>({...baseSlot(s),status:'inactive',actualFrameUID:null,derivationId:null,candidateId:null,actualMasterTime:null,signedDelta:null,missingReason:'role_not_active',mappingUncertaintyUs:null,toleranceUs:null,actualPhaseEvidenceRefs:[],selectionReason:'inactive',sourceId:null,streamGeneration:null,frameSeq:null,contentDigest:null,frameEnvelopeRef:null,contributingReasons:[],phaseProof:null}));return immutablePlainCopy({projectionId,projectionVersion,planVersion,runId,cycleId,masterClockId,role,inputCandidateCount:candidates.length,eligibleCandidateCount:0,inputCandidateDigest:sha256Canonical(candidates),timelineDigest:sha256Canonical(timeline),configDigest,slots:rows,uniqueRealCount:0,missingCount:0,inactiveCount:25});}
  const bindings=normalizeBindings(roleBindings);preflightRawUidConflicts(candidates);const ctx={runId,cycleId,masterClockId,role,bindings},classified=candidates.map(c=>classifyCandidate(c,ctx)),ineligibleReasons=classified.filter(x=>!x.ok).map(x=>x.reason),validRows=classified.filter(x=>x.ok),frames=bestDerivations(validRows),assignment=minCostLexMatch(slots,frames,timeline);
  const used=new Set();const rows=slots.map((s,i)=>{const j=assignment.get(i);if(j===undefined){let reason='no_frame_in_tolerance';if(!Number.isSafeInteger(s.targetMasterTime))reason=s.phase==='release_window'?'release_time_unknown':'phase_unverified';else if(candidates.length===0)reason='no_candidates';else if(validRows.length===0)reason=ineligibleReasons.includes('generation_mismatch')?'generation_mismatch':ineligibleReasons.includes('payload_missing')?'payload_missing':ineligibleReasons.includes('clock_uncertain')?'clock_uncertain':'no_eligible_candidates';else if(frames.length===used.size)reason='unique_frame_exhausted';return {...baseSlot(s),status:'missing',actualFrameUID:null,derivationId:null,candidateId:null,actualMasterTime:null,signedDelta:null,missingReason:reason,mappingUncertaintyUs:null,toleranceUs:null,actualPhaseEvidenceRefs:[],selectionReason:'missing',sourceId:null,streamGeneration:null,frameSeq:null,contentDigest:null,frameEnvelopeRef:null,contributingReasons:[...new Set(ineligibleReasons)],phaseProof:null};}
    const r=frames[j],f=r.value,tol=tolerance(r);used.add(f.frameUID);const timelineRefs=[...(s.targetPhaseEvidenceRefs||[])];const phaseRefs=s.phase==='release_window'?[...timelineRefs,...(f.phaseEvidenceRefs||[])]:timelineRefs;const phaseProof=s.phase==='release_window'?null:{phase:s.phase,timelineRefs,intervalCheck:'inside',settledAnchorBoundary:s.phase==='anchor'};return {...baseSlot(s),status:'real',actualFrameUID:f.frameUID,derivationId:f.derivationId,candidateId:f.candidateId,actualMasterTime:f.actualMasterTime,signedDelta:f.actualMasterTime-s.targetMasterTime,missingReason:null,mappingUncertaintyUs:f.mappingUncertainty,toleranceUs:tol,actualPhaseEvidenceRefs:[...new Set(phaseRefs)],selectionReason:'max_cardinality_min_delta_lexicographic',sourceId:f.sourceId,streamGeneration:f.streamGeneration,frameSeq:f.frameSeq,contentDigest:f.contentDigest,frameEnvelopeRef:f.frameEnvelopeRef,contributingReasons:[],phaseProof};});
  const uniqueRealCount=rows.filter(x=>x.status==='real').length,missingCount=rows.filter(x=>x.status==='missing').length;return immutablePlainCopy({projectionId,projectionVersion,planVersion,runId,cycleId,masterClockId,role,inputCandidateCount:candidates.length,eligibleCandidateCount:validRows.length,inputCandidateDigest:sha256Canonical(candidates),timelineDigest:sha256Canonical(timeline),configDigest,slots:rows,uniqueRealCount,missingCount,inactiveCount:0});
}
module.exports={PLAN,SLOT_PLAN,slotTargets,project25,minCostLexMatch};
