const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const layer=fs.readFileSync(path.join(root,'static','temporal_evidence_layer.js'),'utf8');
const worker=fs.readFileSync(path.join(root,'static','temporal_evidence_worker.js'),'utf8');
const cap=fs.readFileSync(path.join(root,'static','capture_integrity_layer.js'),'utf8');
const launcher=fs.readFileSync(path.join(root,'../internal/start_analyzer.sh'),'utf8');
assert(layer.includes("version:'BLE4.3.7.4'"));
assert(layer.includes('startWorkerTrack'));
assert(layer.includes('startMainTrackProcessor'));
assert(layer.includes('startVideoPump'));
assert(layer.includes("'main-track-processor'"));
assert(layer.includes("'independent-video-pump'"));
assert(layer.includes('attempts:[...s.attempts]'));
assert(worker.includes("m.type==='start_feed'"));
assert(worker.includes("m.type==='feed_frame'"));
assert(worker.includes('recordInterval(s,mediaMs,epochMs)'));
assert(cap.includes("const VERSION='BLE4.3.8.2'"));
assert(cap.includes('temporal_backend:te.backend'));
assert(cap.includes('temporal_error:te.error'));
assert(cap.includes('environment:window.TemporalEvidenceLayer?.browserInfo?.()'));
assert(launcher.includes('3PM UI browser: Google Chrome'));
assert(fs.readFileSync(path.join(root,'static','native_capture_layer.js'),'utf8').includes("version:'HV3-cross-platform-capture-v1'"));
console.log('BLE4.3.7.4 temporal fallback static contract: PASS');
