const fs=require('fs'),assert=require('assert'),vm=require('vm');
const html=fs.readFileSync('static/index.html','utf8'),layer=fs.readFileSync('static/equipment_lab_layer.js','utf8'),app=fs.readFileSync('static/app.js','utf8');
for(const id of ['currentRiserLength','currentLimbBrand','currentLimbModel','currentMarkedDrawWeight','currentVbarVariant','eqlabFactoryShaftLength','eqlabPointReference'])assert(html.includes(`id="${id}"`),id);
assert(html.includes('Actual Cut Shaft Length'),'actual shaft length must be separate from factory reference');
assert(html.includes('Catalog Point Reference'),'point recommendation must be separate from actual point weight');
assert(html.includes('class="hidden" type="checkbox" name="sight"'),'sight fitted state must be derived through hidden compatibility checkbox');
assert(html.includes('class="hidden" type="checkbox" name="clicker"'),'clicker fitted state must be derived through hidden compatibility checkbox');
assert(!layer.includes('const ARROW_DB='),'Pandarus matrix must live in canonical catalog, not form hard-code');
assert(layer.includes("uniq(rs.map(r=>r.model))"),'model selectors must aggregate variants');
assert(layer.includes('collectLimbSizes'),'limb size selector must be model-driven');
assert(layer.includes('collectLimbWeights'),'limb marked draw weight must be model-driven');
assert(layer.includes('setAccessoryMassFromCatalog'),'catalog grams must pass through unit conversion');
assert(layer.includes("currentWeightUnit()==='oz'?v.toFixed(3):v.toFixed(1)"),'g/oz numeric conversion required');
const arrowFn=layer.slice(layer.indexOf('function autoFillArrowSpec(){'),layer.indexOf('let APPSTATE='));
assert(!arrowFn.includes('[name="arrow_length_in"]'),'factory shaft length must not overwrite actual cut length');
assert(!arrowFn.includes('[name="point_weight_gr"]'),'catalog point reference must not overwrite actual point weight');
assert(app.includes('convertEquipmentUnitAwareValues(prev,next)'),'existing values must convert when unit changes');
// Execute the actual Equipment-layer conversion helper with a minimal DOM stub.
const form={elements:{weight_unit:{value:'oz'}}};
const doc={readyState:'loading',querySelector:s=>s==='#equipmentForm'?form:null,querySelectorAll:()=>[],addEventListener:()=>{}};
const ctx={window:{},document:doc,console,Event:function(){},MutationObserver:function(){this.observe=()=>{}}};
vm.createContext(ctx);
const instrumented=layer.replace("if(document.readyState==='loading')", "window.__EL17Test={gramsToCurrent,catalogMassGr,setAccessoryMassFromCatalog};if(document.readyState==='loading')");
vm.runInContext(instrumented,ctx);
const t=ctx.window.__EL17Test;
assert(Math.abs(t.gramsToCurrent(211)-7.4428)<0.001,'211 g Shibuya mass must numerically convert to about 7.443 oz');
const target={value:'',dataset:{}};t.setAccessoryMassFromCatalog(target,{mass_g:211});assert.strictEqual(target.value,'7.443','catalog g→oz autofill must convert numeric value');
form.elements.weight_unit.value='g';const targetG={value:'',dataset:{}};t.setAccessoryMassFromCatalog(targetG,{mass_oz:7.4428});assert(Math.abs(Number(targetG.value)-211)<0.1,'catalog oz→g autofill must convert numeric value');
console.log('PASS Equipment form EL17 normalized UX');
