'use strict';
const assert=require('assert');
const L=require('../static/side_lifecycle_core.js');
assert.equal(L.VERSION,'BLE4.3.8.9.5.5-side-lifecycle-v7');
function f(t,o={}){return {epochMs:t,phaseQuality:.96,phaseDrawWristVisibility:.95,phaseDrawElbowVisibility:.96,setReady:true,physicalSetReady:true,phaseShootingPosture:false,phaseBowExtended:false,bowPlaneReady:false,bowPlaneStable:false,setAdmissionReady:false,shotIntentReady:false,neutralEvidence:true,wristsLow:true,drawSideVisible:true,bowArmDeg:108,bowSpeed:.08,drawSpeed:.08,faceHandSpeed:.08,phaseFaceDist:2.5,...o};}
function live(t,o={}){return f(t,{phaseShootingPosture:true,phaseBowExtended:true,bowPlaneReady:true,bowPlaneStable:true,setAdmissionReady:true,shotIntentReady:true,neutralEvidence:false,wristsLow:false,bowArmDeg:145,bowSpeed:1.0,drawSpeed:1.15,faceHandSpeed:1.0,phaseFaceDist:1.0,...o});}
function native(phase='Setup',o={}){return {phase,primaryPhase:phase,phaseTimeline:o.phaseTimeline||[],...o};}
function boot(){let s=L.fresh();for(const t of [0,110,220])s=L.update(s,f(t),native(),t).state;assert.equal(s.stableSet,true);return s;}
// Exact false-start shape: high movement/raw Draw but no plane/admission => public Set, no cycle.
{let s=boot(),events=[];for(const t of [300,370,440]){const r=L.update(s,f(t,{neutralEvidence:false,wristsLow:false,bowArmDeg:148,bowSpeed:1.4,drawSpeed:1.3,faceHandSpeed:1.4,phaseFaceDist:1.05}),native('Draw',{phaseTimeline:[{phase:'Draw',epochMs:300}]}),t);s=r.state;if(r.event)events.push(r.event);assert.equal(r.snapshot.authorityPhase,'Set');assert.equal(r.snapshot.shotActive,false);}for(const t of [560,800])s=L.update(s,f(t),native(),t).state;assert.equal(events.length,0);assert.equal(s.authorityPhase,'Set');}
// Verified Setup can cancel back to Set; it is not a forbidden regression because Draw was never verified.
{let s=boot(),seenStart=false,seenAbort=false;for(const t of [300,370,440]){const r=L.update(s,live(t,{drawSpeed:.2,faceHandSpeed:.2}),native('Setup'),t);s=r.state;seenStart||=r.event?.type==='shot-start';}assert(seenStart&&s.verifiedSetup&&!s.verifiedDraw);for(const t of [560,700,840]){const r=L.update(s,f(t),native(),t);s=r.state;seenAbort||=r.event?.type==='shot-abort';}assert(seenAbort);assert.equal(s.authorityPhase,'Set');assert.equal(s.shotActive,false);}
// Verified Draw+ is monotonic even if raw core walks backwards.
{let s=boot();for(const t of [300,380])s=L.update(s,live(t),native('Draw',{phaseTimeline:[{phase:'Draw',epochMs:300}]}),t).state;assert.equal(s.verifiedDraw,true);s=L.update(s,live(500,{bowSpeed:.2,drawSpeed:.2,faceHandSpeed:.2}),native('Anchor',{phaseTimeline:[{phase:'Draw',epochMs:300},{phase:'Anchor',epochMs:500}]}),500).state;s=L.update(s,live(600,{bowSpeed:.1,drawSpeed:.1,faceHandSpeed:.1}),native('Aim / Hold',{phaseTimeline:[{phase:'Draw',epochMs:300},{phase:'Anchor',epochMs:500},{phase:'Aim / Hold',epochMs:600}]}),600).state;assert.equal(s.authorityPhase,'Aim / Hold');const r=L.update(s,live(680,{bowSpeed:.1,drawSpeed:.1,faceHandSpeed:.1}),native('Draw',{phaseTimeline:[{phase:'Draw',epochMs:300}]}),680);assert.equal(r.snapshot.authorityPhase,'Aim / Hold');}
// Plan B: missing native let-down edge + sustained trusted neutral still terminates cleanly at Set, no Release invented.
{let s=boot(),evt=null;for(const t of [300,380])s=L.update(s,live(t),native('Draw',{phaseTimeline:[{phase:'Draw',epochMs:300}]}),t).state;for(const t of [500,680,860]){const r=L.update(s,f(t),native('Setup'),t);s=r.state;if(r.event)evt=r.event;}assert.equal(evt?.type,'let-down');assert.equal(evt?.reason,'neutral-fallback');assert.equal(s.authorityPhase,'Set');assert.equal(s.terminal,false);}
// Tracking uncertainty holds trusted phase; it never reverses.
{let s=boot();for(const t of [300,380])s=L.update(s,live(t),native('Draw',{phaseTimeline:[{phase:'Draw',epochMs:300}]}),t).state;s=L.update(s,live(450,{bowSpeed:.1,drawSpeed:.1,faceHandSpeed:.1}),native('Anchor',{phaseTimeline:[{phase:'Draw',epochMs:300},{phase:'Anchor',epochMs:450}]}),450).state;s=L.update(s,live(550,{bowSpeed:.1,drawSpeed:.1,faceHandSpeed:.1}),native('Aim / Hold',{phaseTimeline:[{phase:'Draw',epochMs:300},{phase:'Anchor',epochMs:450},{phase:'Aim / Hold',epochMs:550}]}),550).state;for(const t of [600,650,700]){const r=L.update(s,f(t,{phaseQuality:.04,phaseDrawWristVisibility:.02,phaseDrawElbowVisibility:.03,neutralEvidence:false,wristsLow:false}),native('Setup'),t);s=r.state;assert.equal(r.snapshot.authorityPhase,'Aim / Hold');assert.equal(r.snapshot.shotActive,true);}}
console.log('BLE4.3.8.9.4.1 Trust-First QA PASS · scratch/head movement stays Set · provisional cancel · monotonic verified shot · neutral Plan B · tracking hold');
